image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - rust-lang.rust-analyzer
    - vadimcn.vscode-lldb

github:
  prebuilds:
    addBadge: true
    addComment: true
    pullRequests: true
    pullRequestsFromForks: true
    
 tasks:
 - name: Get 6-1 Repo
 init: git clone https://github.com/stellar/fca00c-asteroids
